version: "3.7"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    container_name: "rabbitmq"
    restart: always
    depends_on:
      - postgre_db
    environment:
      RABBITMQ_DEFAULT_USER: "fast_api_user"
      RABBITMQ_DEFAULT_PASS: "fast_api_pass"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - custom

  postgre_db:
    restart: always
    image: postgres
    hostname: postgre_db
    container_name: "postgre_db"
    environment:
      POSTGRES_USER: fast_api
      POSTGRES_PASSWORD: pgpwd4habr
      POSTGRES_DB: fast_api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - custom

  test_postgre_db:
    restart: always
    image: postgres
    hostname: test_postgre_db
    container_name: "test_postgre_db"
    environment:
      POSTGRES_USER: fast_api
      POSTGRES_PASSWORD: pgpwd4habr
      POSTGRES_DB: test_fast_api
    ports:
      - "5432:5434"
    networks:
      - custom

  app:
    container_name: "app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgre_db
      - test_postgre_db
      - rabbitmq
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge
