version: "3.7"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "fast_api_user"
      RABBITMQ_DEFAULT_PASS: "fast_api_pass"
    ports:
      - "15672:15672"
      - "5672:5672"
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: fast_api
      POSTGRES_PASSWORD: pgpwd4habr
      POSTGRES_DB: fast_api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
