"""Create database

Revision ID: f27785cef7bf
Revises: 
Create Date: 2024-02-02 10:25:46.796888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27785cef7bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('enrollment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('major', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    # op.drop_index('date_of_birth_index', table_name='student')
    # op.drop_index('student_index', table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('student_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('enrollment_date', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('major', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('student_id', name='student_pkey')
    )
    # op.create_index('student_index', 'student', ['student_id'], unique=False)
    # op.create_index('date_of_birth_index', 'student', ['date_of_birth'], unique=False)
    op.drop_table('students')
    # ### end Alembic commands ###
